version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - 9091:9090
    expose:
      - 9091
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=root
      - POSTGRES_DB=meteo
    container_name: postgres

  backend:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    expose:
      - 8080
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - postgres
    links:
      - postgres
    container_name: spring

  prometheus:
    image: prom/prometheus:v2.3.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:5.2.2
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./grafana.env
#
#  frontend:
#    container_name: react
#    build:
#      context: ./frontend
#    command: npm start
#    volumes:
#      - .:/frontend
#      - /frontend/node_modules
#    ports:
#      - 8181:8081
#    environment:
#      - NODE_ENV=development
#    depends_on:
#      - backend